// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.1
// source: cart_snapshot_service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import Long from "long";
import _m0 from "protobufjs/minimal";
import { CartItem } from "./cart";

export const protobufPackage = "cart_snapshot_service";

/** Represents an immutable snapshot of a user's cart at the point of checkout initiation */
export interface CartSnapshot {
  snapshotId: string;
  userId: string;
  items: CartItem[];
  totalPriceCents: number;
  totalDiscountCents: number;
  totalTaxCents: number;
  /** For simplicity, a string representation of the address */
  shippingAddress: string;
  /** ISO 8601 format timestamp */
  createdAt: string;
}

/** Request to create a cart snapshot */
export interface CreateCartSnapshotRequest {
  userId: string;
  cartItems: CartItem[];
  totalPriceCents: number;
  totalDiscountCents: number;
  totalTaxCents: number;
  shippingAddress: string;
}

/** Response after creating a cart snapshot */
export interface CreateCartSnapshotResponse {
  snapshotId: string;
  success: boolean;
  message: string;
}

/** Request to retrieve a cart snapshot */
export interface GetCartSnapshotRequest {
  snapshotId: string;
}

/** Response containing the requested cart snapshot */
export interface CartSnapshotResponse {
  snapshot: CartSnapshot | undefined;
  success: boolean;
  message: string;
}

function createBaseCartSnapshot(): CartSnapshot {
  return {
    snapshotId: "",
    userId: "",
    items: [],
    totalPriceCents: 0,
    totalDiscountCents: 0,
    totalTaxCents: 0,
    shippingAddress: "",
    createdAt: "",
  };
}

export const CartSnapshot = {
  encode(
    message: CartSnapshot,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.snapshotId !== "") {
      writer.uint32(10).string(message.snapshotId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    for (const v of message.items) {
      CartItem.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    if (message.totalPriceCents !== 0) {
      writer.uint32(32).int64(message.totalPriceCents);
    }
    if (message.totalDiscountCents !== 0) {
      writer.uint32(40).int64(message.totalDiscountCents);
    }
    if (message.totalTaxCents !== 0) {
      writer.uint32(48).int64(message.totalTaxCents);
    }
    if (message.shippingAddress !== "") {
      writer.uint32(58).string(message.shippingAddress);
    }
    if (message.createdAt !== "") {
      writer.uint32(66).string(message.createdAt);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CartSnapshot {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCartSnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.snapshotId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.items.push(CartItem.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.totalPriceCents = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.totalDiscountCents = longToNumber(reader.int64() as Long);
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.totalTaxCents = longToNumber(reader.int64() as Long);
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.shippingAddress = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.createdAt = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CartSnapshot {
    return {
      snapshotId: isSet(object.snapshotId)
        ? globalThis.String(object.snapshotId)
        : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => CartItem.fromJSON(e))
        : [],
      totalPriceCents: isSet(object.totalPriceCents)
        ? globalThis.Number(object.totalPriceCents)
        : 0,
      totalDiscountCents: isSet(object.totalDiscountCents)
        ? globalThis.Number(object.totalDiscountCents)
        : 0,
      totalTaxCents: isSet(object.totalTaxCents)
        ? globalThis.Number(object.totalTaxCents)
        : 0,
      shippingAddress: isSet(object.shippingAddress)
        ? globalThis.String(object.shippingAddress)
        : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : "",
    };
  },

  toJSON(message: CartSnapshot): unknown {
    const obj: any = {};
    if (message.snapshotId !== "") {
      obj.snapshotId = message.snapshotId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => CartItem.toJSON(e));
    }
    if (message.totalPriceCents !== 0) {
      obj.totalPriceCents = Math.round(message.totalPriceCents);
    }
    if (message.totalDiscountCents !== 0) {
      obj.totalDiscountCents = Math.round(message.totalDiscountCents);
    }
    if (message.totalTaxCents !== 0) {
      obj.totalTaxCents = Math.round(message.totalTaxCents);
    }
    if (message.shippingAddress !== "") {
      obj.shippingAddress = message.shippingAddress;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CartSnapshot>, I>>(
    base?: I,
  ): CartSnapshot {
    return CartSnapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CartSnapshot>, I>>(
    object: I,
  ): CartSnapshot {
    const message = createBaseCartSnapshot();
    message.snapshotId = object.snapshotId ?? "";
    message.userId = object.userId ?? "";
    message.items = object.items?.map((e) => CartItem.fromPartial(e)) || [];
    message.totalPriceCents = object.totalPriceCents ?? 0;
    message.totalDiscountCents = object.totalDiscountCents ?? 0;
    message.totalTaxCents = object.totalTaxCents ?? 0;
    message.shippingAddress = object.shippingAddress ?? "";
    message.createdAt = object.createdAt ?? "";
    return message;
  },
};

function createBaseCreateCartSnapshotRequest(): CreateCartSnapshotRequest {
  return {
    userId: "",
    cartItems: [],
    totalPriceCents: 0,
    totalDiscountCents: 0,
    totalTaxCents: 0,
    shippingAddress: "",
  };
}

export const CreateCartSnapshotRequest = {
  encode(
    message: CreateCartSnapshotRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    for (const v of message.cartItems) {
      CartItem.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    if (message.totalPriceCents !== 0) {
      writer.uint32(24).int64(message.totalPriceCents);
    }
    if (message.totalDiscountCents !== 0) {
      writer.uint32(32).int64(message.totalDiscountCents);
    }
    if (message.totalTaxCents !== 0) {
      writer.uint32(40).int64(message.totalTaxCents);
    }
    if (message.shippingAddress !== "") {
      writer.uint32(50).string(message.shippingAddress);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CreateCartSnapshotRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCartSnapshotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.cartItems.push(CartItem.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.totalPriceCents = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.totalDiscountCents = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.totalTaxCents = longToNumber(reader.int64() as Long);
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.shippingAddress = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCartSnapshotRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      cartItems: globalThis.Array.isArray(object?.cartItems)
        ? object.cartItems.map((e: any) => CartItem.fromJSON(e))
        : [],
      totalPriceCents: isSet(object.totalPriceCents)
        ? globalThis.Number(object.totalPriceCents)
        : 0,
      totalDiscountCents: isSet(object.totalDiscountCents)
        ? globalThis.Number(object.totalDiscountCents)
        : 0,
      totalTaxCents: isSet(object.totalTaxCents)
        ? globalThis.Number(object.totalTaxCents)
        : 0,
      shippingAddress: isSet(object.shippingAddress)
        ? globalThis.String(object.shippingAddress)
        : "",
    };
  },

  toJSON(message: CreateCartSnapshotRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.cartItems?.length) {
      obj.cartItems = message.cartItems.map((e) => CartItem.toJSON(e));
    }
    if (message.totalPriceCents !== 0) {
      obj.totalPriceCents = Math.round(message.totalPriceCents);
    }
    if (message.totalDiscountCents !== 0) {
      obj.totalDiscountCents = Math.round(message.totalDiscountCents);
    }
    if (message.totalTaxCents !== 0) {
      obj.totalTaxCents = Math.round(message.totalTaxCents);
    }
    if (message.shippingAddress !== "") {
      obj.shippingAddress = message.shippingAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCartSnapshotRequest>, I>>(
    base?: I,
  ): CreateCartSnapshotRequest {
    return CreateCartSnapshotRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCartSnapshotRequest>, I>>(
    object: I,
  ): CreateCartSnapshotRequest {
    const message = createBaseCreateCartSnapshotRequest();
    message.userId = object.userId ?? "";
    message.cartItems =
      object.cartItems?.map((e) => CartItem.fromPartial(e)) || [];
    message.totalPriceCents = object.totalPriceCents ?? 0;
    message.totalDiscountCents = object.totalDiscountCents ?? 0;
    message.totalTaxCents = object.totalTaxCents ?? 0;
    message.shippingAddress = object.shippingAddress ?? "";
    return message;
  },
};

function createBaseCreateCartSnapshotResponse(): CreateCartSnapshotResponse {
  return { snapshotId: "", success: false, message: "" };
}

export const CreateCartSnapshotResponse = {
  encode(
    message: CreateCartSnapshotResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.snapshotId !== "") {
      writer.uint32(10).string(message.snapshotId);
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CreateCartSnapshotResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCartSnapshotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.snapshotId = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCartSnapshotResponse {
    return {
      snapshotId: isSet(object.snapshotId)
        ? globalThis.String(object.snapshotId)
        : "",
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: CreateCartSnapshotResponse): unknown {
    const obj: any = {};
    if (message.snapshotId !== "") {
      obj.snapshotId = message.snapshotId;
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCartSnapshotResponse>, I>>(
    base?: I,
  ): CreateCartSnapshotResponse {
    return CreateCartSnapshotResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCartSnapshotResponse>, I>>(
    object: I,
  ): CreateCartSnapshotResponse {
    const message = createBaseCreateCartSnapshotResponse();
    message.snapshotId = object.snapshotId ?? "";
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseGetCartSnapshotRequest(): GetCartSnapshotRequest {
  return { snapshotId: "" };
}

export const GetCartSnapshotRequest = {
  encode(
    message: GetCartSnapshotRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.snapshotId !== "") {
      writer.uint32(10).string(message.snapshotId);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): GetCartSnapshotRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCartSnapshotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.snapshotId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCartSnapshotRequest {
    return {
      snapshotId: isSet(object.snapshotId)
        ? globalThis.String(object.snapshotId)
        : "",
    };
  },

  toJSON(message: GetCartSnapshotRequest): unknown {
    const obj: any = {};
    if (message.snapshotId !== "") {
      obj.snapshotId = message.snapshotId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCartSnapshotRequest>, I>>(
    base?: I,
  ): GetCartSnapshotRequest {
    return GetCartSnapshotRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCartSnapshotRequest>, I>>(
    object: I,
  ): GetCartSnapshotRequest {
    const message = createBaseGetCartSnapshotRequest();
    message.snapshotId = object.snapshotId ?? "";
    return message;
  },
};

function createBaseCartSnapshotResponse(): CartSnapshotResponse {
  return { snapshot: undefined, success: false, message: "" };
}

export const CartSnapshotResponse = {
  encode(
    message: CartSnapshotResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.snapshot !== undefined) {
      CartSnapshot.encode(message.snapshot, writer.uint32(10).fork()).ldelim();
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CartSnapshotResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCartSnapshotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.snapshot = CartSnapshot.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CartSnapshotResponse {
    return {
      snapshot: isSet(object.snapshot)
        ? CartSnapshot.fromJSON(object.snapshot)
        : undefined,
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: CartSnapshotResponse): unknown {
    const obj: any = {};
    if (message.snapshot !== undefined) {
      obj.snapshot = CartSnapshot.toJSON(message.snapshot);
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CartSnapshotResponse>, I>>(
    base?: I,
  ): CartSnapshotResponse {
    return CartSnapshotResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CartSnapshotResponse>, I>>(
    object: I,
  ): CartSnapshotResponse {
    const message = createBaseCartSnapshotResponse();
    message.snapshot =
      object.snapshot !== undefined && object.snapshot !== null
        ? CartSnapshot.fromPartial(object.snapshot)
        : undefined;
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

/** Service for creating and retrieving cart snapshots */
export type CartSnapshotServiceService = typeof CartSnapshotServiceService;
export const CartSnapshotServiceService = {
  /** Creates an immutable snapshot of the cart for checkout initiation */
  createCartSnapshot: {
    path: "/cart_snapshot_service.CartSnapshotService/CreateCartSnapshot",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateCartSnapshotRequest) =>
      Buffer.from(CreateCartSnapshotRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) =>
      CreateCartSnapshotRequest.decode(value),
    responseSerialize: (value: CreateCartSnapshotResponse) =>
      Buffer.from(CreateCartSnapshotResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) =>
      CreateCartSnapshotResponse.decode(value),
  },
  /** Retrieves a specific cart snapshot by its ID */
  getCartSnapshot: {
    path: "/cart_snapshot_service.CartSnapshotService/GetCartSnapshot",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetCartSnapshotRequest) =>
      Buffer.from(GetCartSnapshotRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetCartSnapshotRequest.decode(value),
    responseSerialize: (value: CartSnapshotResponse) =>
      Buffer.from(CartSnapshotResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CartSnapshotResponse.decode(value),
  },
} as const;

export interface CartSnapshotServiceServer
  extends UntypedServiceImplementation {
  /** Creates an immutable snapshot of the cart for checkout initiation */
  createCartSnapshot: handleUnaryCall<
    CreateCartSnapshotRequest,
    CreateCartSnapshotResponse
  >;
  /** Retrieves a specific cart snapshot by its ID */
  getCartSnapshot: handleUnaryCall<
    GetCartSnapshotRequest,
    CartSnapshotResponse
  >;
}

export interface CartSnapshotServiceClient extends Client {
  /** Creates an immutable snapshot of the cart for checkout initiation */
  createCartSnapshot(
    request: CreateCartSnapshotRequest,
    callback: (
      error: ServiceError | null,
      response: CreateCartSnapshotResponse,
    ) => void,
  ): ClientUnaryCall;
  createCartSnapshot(
    request: CreateCartSnapshotRequest,
    metadata: Metadata,
    callback: (
      error: ServiceError | null,
      response: CreateCartSnapshotResponse,
    ) => void,
  ): ClientUnaryCall;
  createCartSnapshot(
    request: CreateCartSnapshotRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (
      error: ServiceError | null,
      response: CreateCartSnapshotResponse,
    ) => void,
  ): ClientUnaryCall;
  /** Retrieves a specific cart snapshot by its ID */
  getCartSnapshot(
    request: GetCartSnapshotRequest,
    callback: (
      error: ServiceError | null,
      response: CartSnapshotResponse,
    ) => void,
  ): ClientUnaryCall;
  getCartSnapshot(
    request: GetCartSnapshotRequest,
    metadata: Metadata,
    callback: (
      error: ServiceError | null,
      response: CartSnapshotResponse,
    ) => void,
  ): ClientUnaryCall;
  getCartSnapshot(
    request: GetCartSnapshotRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (
      error: ServiceError | null,
      response: CartSnapshotResponse,
    ) => void,
  ): ClientUnaryCall;
}

export const CartSnapshotServiceClient = makeGenericClientConstructor(
  CartSnapshotServiceService,
  "cart_snapshot_service.CartSnapshotService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): CartSnapshotServiceClient;
  service: typeof CartSnapshotServiceService;
  serviceName: string;
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
