// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.1
// source: product_read_service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { Product } from "./product";

export const protobufPackage = "product_read";

export interface GetProductByIdRequest {
  id: string;
}

export interface GetAllProductsRequest {}

export interface GetAllProductsResponse {
  products: Product[];
}

export interface SearchProductsRequest {
  query: string;
}

export interface SearchProductsResponse {
  products: Product[];
}

/** Request to get details for a product */
export interface GetProductDetailsRequest {
  productId: string;
}

function createBaseGetProductByIdRequest(): GetProductByIdRequest {
  return { id: "" };
}

export const GetProductByIdRequest = {
  encode(
    message: GetProductByIdRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): GetProductByIdRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProductByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetProductByIdRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetProductByIdRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetProductByIdRequest>, I>>(
    base?: I,
  ): GetProductByIdRequest {
    return GetProductByIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetProductByIdRequest>, I>>(
    object: I,
  ): GetProductByIdRequest {
    const message = createBaseGetProductByIdRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetAllProductsRequest(): GetAllProductsRequest {
  return {};
}

export const GetAllProductsRequest = {
  encode(
    _: GetAllProductsRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): GetAllProductsRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllProductsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetAllProductsRequest {
    return {};
  },

  toJSON(_: GetAllProductsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAllProductsRequest>, I>>(
    base?: I,
  ): GetAllProductsRequest {
    return GetAllProductsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAllProductsRequest>, I>>(
    _: I,
  ): GetAllProductsRequest {
    const message = createBaseGetAllProductsRequest();
    return message;
  },
};

function createBaseGetAllProductsResponse(): GetAllProductsResponse {
  return { products: [] };
}

export const GetAllProductsResponse = {
  encode(
    message: GetAllProductsResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    for (const v of message.products) {
      Product.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): GetAllProductsResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllProductsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.products.push(Product.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAllProductsResponse {
    return {
      products: globalThis.Array.isArray(object?.products)
        ? object.products.map((e: any) => Product.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetAllProductsResponse): unknown {
    const obj: any = {};
    if (message.products?.length) {
      obj.products = message.products.map((e) => Product.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAllProductsResponse>, I>>(
    base?: I,
  ): GetAllProductsResponse {
    return GetAllProductsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAllProductsResponse>, I>>(
    object: I,
  ): GetAllProductsResponse {
    const message = createBaseGetAllProductsResponse();
    message.products =
      object.products?.map((e) => Product.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSearchProductsRequest(): SearchProductsRequest {
  return { query: "" };
}

export const SearchProductsRequest = {
  encode(
    message: SearchProductsRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): SearchProductsRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchProductsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.query = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchProductsRequest {
    return {
      query: isSet(object.query) ? globalThis.String(object.query) : "",
    };
  },

  toJSON(message: SearchProductsRequest): unknown {
    const obj: any = {};
    if (message.query !== "") {
      obj.query = message.query;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchProductsRequest>, I>>(
    base?: I,
  ): SearchProductsRequest {
    return SearchProductsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchProductsRequest>, I>>(
    object: I,
  ): SearchProductsRequest {
    const message = createBaseSearchProductsRequest();
    message.query = object.query ?? "";
    return message;
  },
};

function createBaseSearchProductsResponse(): SearchProductsResponse {
  return { products: [] };
}

export const SearchProductsResponse = {
  encode(
    message: SearchProductsResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    for (const v of message.products) {
      Product.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): SearchProductsResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchProductsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.products.push(Product.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchProductsResponse {
    return {
      products: globalThis.Array.isArray(object?.products)
        ? object.products.map((e: any) => Product.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SearchProductsResponse): unknown {
    const obj: any = {};
    if (message.products?.length) {
      obj.products = message.products.map((e) => Product.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchProductsResponse>, I>>(
    base?: I,
  ): SearchProductsResponse {
    return SearchProductsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchProductsResponse>, I>>(
    object: I,
  ): SearchProductsResponse {
    const message = createBaseSearchProductsResponse();
    message.products =
      object.products?.map((e) => Product.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetProductDetailsRequest(): GetProductDetailsRequest {
  return { productId: "" };
}

export const GetProductDetailsRequest = {
  encode(
    message: GetProductDetailsRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): GetProductDetailsRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProductDetailsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetProductDetailsRequest {
    return {
      productId: isSet(object.productId)
        ? globalThis.String(object.productId)
        : "",
    };
  },

  toJSON(message: GetProductDetailsRequest): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetProductDetailsRequest>, I>>(
    base?: I,
  ): GetProductDetailsRequest {
    return GetProductDetailsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetProductDetailsRequest>, I>>(
    object: I,
  ): GetProductDetailsRequest {
    const message = createBaseGetProductDetailsRequest();
    message.productId = object.productId ?? "";
    return message;
  },
};

export type ProductReadServiceService = typeof ProductReadServiceService;
export const ProductReadServiceService = {
  getProductById: {
    path: "/product_read.ProductReadService/GetProductById",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetProductByIdRequest) =>
      Buffer.from(GetProductByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetProductByIdRequest.decode(value),
    responseSerialize: (value: Product) =>
      Buffer.from(Product.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Product.decode(value),
  },
  getAllProducts: {
    path: "/product_read.ProductReadService/GetAllProducts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetAllProductsRequest) =>
      Buffer.from(GetAllProductsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetAllProductsRequest.decode(value),
    responseSerialize: (value: GetAllProductsResponse) =>
      Buffer.from(GetAllProductsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) =>
      GetAllProductsResponse.decode(value),
  },
  searchProducts: {
    path: "/product_read.ProductReadService/SearchProducts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SearchProductsRequest) =>
      Buffer.from(SearchProductsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SearchProductsRequest.decode(value),
    responseSerialize: (value: SearchProductsResponse) =>
      Buffer.from(SearchProductsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) =>
      SearchProductsResponse.decode(value),
  },
  /** Retrieves details for a specific product */
  getProductDetails: {
    path: "/product_read.ProductReadService/GetProductDetails",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetProductDetailsRequest) =>
      Buffer.from(GetProductDetailsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) =>
      GetProductDetailsRequest.decode(value),
    responseSerialize: (value: Product) =>
      Buffer.from(Product.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Product.decode(value),
  },
} as const;

export interface ProductReadServiceServer extends UntypedServiceImplementation {
  getProductById: handleUnaryCall<GetProductByIdRequest, Product>;
  getAllProducts: handleUnaryCall<
    GetAllProductsRequest,
    GetAllProductsResponse
  >;
  searchProducts: handleUnaryCall<
    SearchProductsRequest,
    SearchProductsResponse
  >;
  /** Retrieves details for a specific product */
  getProductDetails: handleUnaryCall<GetProductDetailsRequest, Product>;
}

export interface ProductReadServiceClient extends Client {
  getProductById(
    request: GetProductByIdRequest,
    callback: (error: ServiceError | null, response: Product) => void,
  ): ClientUnaryCall;
  getProductById(
    request: GetProductByIdRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Product) => void,
  ): ClientUnaryCall;
  getProductById(
    request: GetProductByIdRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Product) => void,
  ): ClientUnaryCall;
  getAllProducts(
    request: GetAllProductsRequest,
    callback: (
      error: ServiceError | null,
      response: GetAllProductsResponse,
    ) => void,
  ): ClientUnaryCall;
  getAllProducts(
    request: GetAllProductsRequest,
    metadata: Metadata,
    callback: (
      error: ServiceError | null,
      response: GetAllProductsResponse,
    ) => void,
  ): ClientUnaryCall;
  getAllProducts(
    request: GetAllProductsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (
      error: ServiceError | null,
      response: GetAllProductsResponse,
    ) => void,
  ): ClientUnaryCall;
  searchProducts(
    request: SearchProductsRequest,
    callback: (
      error: ServiceError | null,
      response: SearchProductsResponse,
    ) => void,
  ): ClientUnaryCall;
  searchProducts(
    request: SearchProductsRequest,
    metadata: Metadata,
    callback: (
      error: ServiceError | null,
      response: SearchProductsResponse,
    ) => void,
  ): ClientUnaryCall;
  searchProducts(
    request: SearchProductsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (
      error: ServiceError | null,
      response: SearchProductsResponse,
    ) => void,
  ): ClientUnaryCall;
  /** Retrieves details for a specific product */
  getProductDetails(
    request: GetProductDetailsRequest,
    callback: (error: ServiceError | null, response: Product) => void,
  ): ClientUnaryCall;
  getProductDetails(
    request: GetProductDetailsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Product) => void,
  ): ClientUnaryCall;
  getProductDetails(
    request: GetProductDetailsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Product) => void,
  ): ClientUnaryCall;
}

export const ProductReadServiceClient = makeGenericClientConstructor(
  ProductReadServiceService,
  "product_read.ProductReadService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): ProductReadServiceClient;
  service: typeof ProductReadServiceService;
  serviceName: string;
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
