// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.1
// source: inventory.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal.js";

export const protobufPackage = "inventory";

/** Request to check stock for a given product and quantity */
export interface CheckStockRequest {
  productId: string;
  /** The quantity to check availability for */
  quantity: number;
}

/** Response indicating stock availability and current level */
export interface CheckStockResponse {
  productId: string;
  available: boolean;
  currentStock: number;
  /** Optional message, e.g., "Not enough stock" */
  message: string;
}

function createBaseCheckStockRequest(): CheckStockRequest {
  return { productId: "", quantity: 0 };
}

export const CheckStockRequest = {
  encode(
    message: CheckStockRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    if (message.quantity !== 0) {
      writer.uint32(16).int32(message.quantity);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CheckStockRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckStockRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.quantity = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckStockRequest {
    return {
      productId: isSet(object.productId)
        ? globalThis.String(object.productId)
        : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
    };
  },

  toJSON(message: CheckStockRequest): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckStockRequest>, I>>(
    base?: I,
  ): CheckStockRequest {
    return CheckStockRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckStockRequest>, I>>(
    object: I,
  ): CheckStockRequest {
    const message = createBaseCheckStockRequest();
    message.productId = object.productId ?? "";
    message.quantity = object.quantity ?? 0;
    return message;
  },
};

function createBaseCheckStockResponse(): CheckStockResponse {
  return { productId: "", available: false, currentStock: 0, message: "" };
}

export const CheckStockResponse = {
  encode(
    message: CheckStockResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    if (message.available !== false) {
      writer.uint32(16).bool(message.available);
    }
    if (message.currentStock !== 0) {
      writer.uint32(24).int32(message.currentStock);
    }
    if (message.message !== "") {
      writer.uint32(34).string(message.message);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CheckStockResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckStockResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.available = reader.bool();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.currentStock = reader.int32();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckStockResponse {
    return {
      productId: isSet(object.productId)
        ? globalThis.String(object.productId)
        : "",
      available: isSet(object.available)
        ? globalThis.Boolean(object.available)
        : false,
      currentStock: isSet(object.currentStock)
        ? globalThis.Number(object.currentStock)
        : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: CheckStockResponse): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.available !== false) {
      obj.available = message.available;
    }
    if (message.currentStock !== 0) {
      obj.currentStock = Math.round(message.currentStock);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckStockResponse>, I>>(
    base?: I,
  ): CheckStockResponse {
    return CheckStockResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckStockResponse>, I>>(
    object: I,
  ): CheckStockResponse {
    const message = createBaseCheckStockResponse();
    message.productId = object.productId ?? "";
    message.available = object.available ?? false;
    message.currentStock = object.currentStock ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

/** Service for checking and potentially managing inventory levels */
export type InventoryServiceService = typeof InventoryServiceService;
export const InventoryServiceService = {
  /** Checks the current stock level for a product */
  checkStock: {
    path: "/inventory.InventoryService/CheckStock",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CheckStockRequest) =>
      Buffer.from(CheckStockRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CheckStockRequest.decode(value),
    responseSerialize: (value: CheckStockResponse) =>
      Buffer.from(CheckStockResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CheckStockResponse.decode(value),
  },
} as const;

export interface InventoryServiceServer extends UntypedServiceImplementation {
  /** Checks the current stock level for a product */
  checkStock: handleUnaryCall<CheckStockRequest, CheckStockResponse>;
}

export interface InventoryServiceClient extends Client {
  /** Checks the current stock level for a product */
  checkStock(
    request: CheckStockRequest,
    callback: (
      error: ServiceError | null,
      response: CheckStockResponse,
    ) => void,
  ): ClientUnaryCall;
  checkStock(
    request: CheckStockRequest,
    metadata: Metadata,
    callback: (
      error: ServiceError | null,
      response: CheckStockResponse,
    ) => void,
  ): ClientUnaryCall;
  checkStock(
    request: CheckStockRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (
      error: ServiceError | null,
      response: CheckStockResponse,
    ) => void,
  ): ClientUnaryCall;
}

export const InventoryServiceClient = makeGenericClientConstructor(
  InventoryServiceService,
  "inventory.InventoryService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): InventoryServiceClient;
  service: typeof InventoryServiceService;
  serviceName: string;
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
