# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cart_pb2 as cart__pb2


class CartServiceStub(object):
  """--- CartService Definition ---
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddItemToCart = channel.unary_unary(
        '/cart.CartService/AddItemToCart',
        request_serializer=cart__pb2.AddItemToCartRequest.SerializeToString,
        response_deserializer=cart__pb2.CartResponse.FromString,
        )
    self.UpdateItemQuantity = channel.unary_unary(
        '/cart.CartService/UpdateItemQuantity',
        request_serializer=cart__pb2.UpdateItemQuantityRequest.SerializeToString,
        response_deserializer=cart__pb2.CartResponse.FromString,
        )
    self.RemoveItemFromCart = channel.unary_unary(
        '/cart.CartService/RemoveItemFromCart',
        request_serializer=cart__pb2.RemoveItemFromCartRequest.SerializeToString,
        response_deserializer=cart__pb2.CartResponse.FromString,
        )
    self.GetCart = channel.unary_unary(
        '/cart.CartService/GetCart',
        request_serializer=cart__pb2.GetCartRequest.SerializeToString,
        response_deserializer=cart__pb2.CartResponse.FromString,
        )


class CartServiceServicer(object):
  """--- CartService Definition ---
  """

  def AddItemToCart(self, request, context):
    """Adds an item to the user's cart or updates its quantity if already present
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateItemQuantity(self, request, context):
    """Updates the quantity of an existing item in the cart
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveItemFromCart(self, request, context):
    """Removes an item from the user's cart
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCart(self, request, context):
    """Retrieves the current state of the user's cart
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CartServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddItemToCart': grpc.unary_unary_rpc_method_handler(
          servicer.AddItemToCart,
          request_deserializer=cart__pb2.AddItemToCartRequest.FromString,
          response_serializer=cart__pb2.CartResponse.SerializeToString,
      ),
      'UpdateItemQuantity': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateItemQuantity,
          request_deserializer=cart__pb2.UpdateItemQuantityRequest.FromString,
          response_serializer=cart__pb2.CartResponse.SerializeToString,
      ),
      'RemoveItemFromCart': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveItemFromCart,
          request_deserializer=cart__pb2.RemoveItemFromCartRequest.FromString,
          response_serializer=cart__pb2.CartResponse.SerializeToString,
      ),
      'GetCart': grpc.unary_unary_rpc_method_handler(
          servicer.GetCart,
          request_deserializer=cart__pb2.GetCartRequest.FromString,
          response_serializer=cart__pb2.CartResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cart.CartService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
