# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cart.proto',
  package='cart',
  syntax='proto3',
  serialized_pb=_b('\n\ncart.proto\x12\x04\x63\x61rt\"0\n\x08\x43\x61rtItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"6\n\x04\x43\x61rt\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1d\n\x05items\x18\x02 \x03(\x0b\x32\x0e.cart.CartItem\"M\n\x14\x41\x64\x64ItemToCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"R\n\x19UpdateItemQuantityRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"@\n\x19RemoveItemFromCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\"!\n\x0eGetCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"(\n\x0c\x43\x61rtResponse\x12\x18\n\x04\x63\x61rt\x18\x01 \x01(\x0b\x32\n.cart.Cart2\x99\x02\n\x0b\x43\x61rtService\x12?\n\rAddItemToCart\x12\x1a.cart.AddItemToCartRequest\x1a\x12.cart.CartResponse\x12I\n\x12UpdateItemQuantity\x12\x1f.cart.UpdateItemQuantityRequest\x1a\x12.cart.CartResponse\x12I\n\x12RemoveItemFromCart\x12\x1f.cart.RemoveItemFromCartRequest\x1a\x12.cart.CartResponse\x12\x33\n\x07GetCart\x12\x14.cart.GetCartRequest\x1a\x12.cart.CartResponseb\x06proto3')
)




_CARTITEM = _descriptor.Descriptor(
  name='CartItem',
  full_name='cart.CartItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='cart.CartItem.product_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='cart.CartItem.quantity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=68,
)


_CART = _descriptor.Descriptor(
  name='Cart',
  full_name='cart.Cart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='cart.Cart.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='cart.Cart.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=124,
)


_ADDITEMTOCARTREQUEST = _descriptor.Descriptor(
  name='AddItemToCartRequest',
  full_name='cart.AddItemToCartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='cart.AddItemToCartRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='cart.AddItemToCartRequest.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='cart.AddItemToCartRequest.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=203,
)


_UPDATEITEMQUANTITYREQUEST = _descriptor.Descriptor(
  name='UpdateItemQuantityRequest',
  full_name='cart.UpdateItemQuantityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='cart.UpdateItemQuantityRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='cart.UpdateItemQuantityRequest.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='cart.UpdateItemQuantityRequest.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=287,
)


_REMOVEITEMFROMCARTREQUEST = _descriptor.Descriptor(
  name='RemoveItemFromCartRequest',
  full_name='cart.RemoveItemFromCartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='cart.RemoveItemFromCartRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='cart.RemoveItemFromCartRequest.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=353,
)


_GETCARTREQUEST = _descriptor.Descriptor(
  name='GetCartRequest',
  full_name='cart.GetCartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='cart.GetCartRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=388,
)


_CARTRESPONSE = _descriptor.Descriptor(
  name='CartResponse',
  full_name='cart.CartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cart', full_name='cart.CartResponse.cart', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=430,
)

_CART.fields_by_name['items'].message_type = _CARTITEM
_CARTRESPONSE.fields_by_name['cart'].message_type = _CART
DESCRIPTOR.message_types_by_name['CartItem'] = _CARTITEM
DESCRIPTOR.message_types_by_name['Cart'] = _CART
DESCRIPTOR.message_types_by_name['AddItemToCartRequest'] = _ADDITEMTOCARTREQUEST
DESCRIPTOR.message_types_by_name['UpdateItemQuantityRequest'] = _UPDATEITEMQUANTITYREQUEST
DESCRIPTOR.message_types_by_name['RemoveItemFromCartRequest'] = _REMOVEITEMFROMCARTREQUEST
DESCRIPTOR.message_types_by_name['GetCartRequest'] = _GETCARTREQUEST
DESCRIPTOR.message_types_by_name['CartResponse'] = _CARTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CartItem = _reflection.GeneratedProtocolMessageType('CartItem', (_message.Message,), dict(
  DESCRIPTOR = _CARTITEM,
  __module__ = 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart.CartItem)
  ))
_sym_db.RegisterMessage(CartItem)

Cart = _reflection.GeneratedProtocolMessageType('Cart', (_message.Message,), dict(
  DESCRIPTOR = _CART,
  __module__ = 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart.Cart)
  ))
_sym_db.RegisterMessage(Cart)

AddItemToCartRequest = _reflection.GeneratedProtocolMessageType('AddItemToCartRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDITEMTOCARTREQUEST,
  __module__ = 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart.AddItemToCartRequest)
  ))
_sym_db.RegisterMessage(AddItemToCartRequest)

UpdateItemQuantityRequest = _reflection.GeneratedProtocolMessageType('UpdateItemQuantityRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEITEMQUANTITYREQUEST,
  __module__ = 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart.UpdateItemQuantityRequest)
  ))
_sym_db.RegisterMessage(UpdateItemQuantityRequest)

RemoveItemFromCartRequest = _reflection.GeneratedProtocolMessageType('RemoveItemFromCartRequest', (_message.Message,), dict(
  DESCRIPTOR = _REMOVEITEMFROMCARTREQUEST,
  __module__ = 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart.RemoveItemFromCartRequest)
  ))
_sym_db.RegisterMessage(RemoveItemFromCartRequest)

GetCartRequest = _reflection.GeneratedProtocolMessageType('GetCartRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCARTREQUEST,
  __module__ = 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart.GetCartRequest)
  ))
_sym_db.RegisterMessage(GetCartRequest)

CartResponse = _reflection.GeneratedProtocolMessageType('CartResponse', (_message.Message,), dict(
  DESCRIPTOR = _CARTRESPONSE,
  __module__ = 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart.CartResponse)
  ))
_sym_db.RegisterMessage(CartResponse)



_CARTSERVICE = _descriptor.ServiceDescriptor(
  name='CartService',
  full_name='cart.CartService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=433,
  serialized_end=714,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddItemToCart',
    full_name='cart.CartService.AddItemToCart',
    index=0,
    containing_service=None,
    input_type=_ADDITEMTOCARTREQUEST,
    output_type=_CARTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateItemQuantity',
    full_name='cart.CartService.UpdateItemQuantity',
    index=1,
    containing_service=None,
    input_type=_UPDATEITEMQUANTITYREQUEST,
    output_type=_CARTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveItemFromCart',
    full_name='cart.CartService.RemoveItemFromCart',
    index=2,
    containing_service=None,
    input_type=_REMOVEITEMFROMCARTREQUEST,
    output_type=_CARTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCart',
    full_name='cart.CartService.GetCart',
    index=3,
    containing_service=None,
    input_type=_GETCARTREQUEST,
    output_type=_CARTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARTSERVICE)

DESCRIPTOR.services_by_name['CartService'] = _CARTSERVICE

# @@protoc_insertion_point(module_scope)
