# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import checkout_pb2 as checkout__pb2


class CheckoutServiceStub(object):
  """Service definition for the checkout orchestrator
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InitiateCheckout = channel.unary_unary(
        '/checkout.CheckoutService/InitiateCheckout',
        request_serializer=checkout__pb2.InitiateCheckoutRequest.SerializeToString,
        response_deserializer=checkout__pb2.InitiateCheckoutResponse.FromString,
        )
    self.GetCheckoutStatus = channel.unary_unary(
        '/checkout.CheckoutService/GetCheckoutStatus',
        request_serializer=checkout__pb2.GetCheckoutStatusRequest.SerializeToString,
        response_deserializer=checkout__pb2.GetCheckoutStatusResponse.FromString,
        )


class CheckoutServiceServicer(object):
  """Service definition for the checkout orchestrator
  """

  def InitiateCheckout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCheckoutStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CheckoutServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InitiateCheckout': grpc.unary_unary_rpc_method_handler(
          servicer.InitiateCheckout,
          request_deserializer=checkout__pb2.InitiateCheckoutRequest.FromString,
          response_serializer=checkout__pb2.InitiateCheckoutResponse.SerializeToString,
      ),
      'GetCheckoutStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetCheckoutStatus,
          request_deserializer=checkout__pb2.GetCheckoutStatusRequest.FromString,
          response_serializer=checkout__pb2.GetCheckoutStatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'checkout.CheckoutService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
