# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkout.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='checkout.proto',
  package='checkout',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x63heckout.proto\x12\x08\x63heckout\"*\n\x17InitiateCheckoutRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"/\n\x18InitiateCheckoutResponse\x12\x13\n\x0b\x63heckout_id\x18\x01 \x01(\t\"/\n\x18GetCheckoutStatusRequest\x12\x13\n\x0b\x63heckout_id\x18\x01 \x01(\t\"i\n\x19GetCheckoutStatusResponse\x12\x13\n\x0b\x63heckout_id\x18\x01 \x01(\t\x12&\n\x05state\x18\x02 \x01(\x0e\x32\x17.checkout.CheckoutState\x12\x0f\n\x07message\x18\x03 \x01(\t*m\n\rCheckoutState\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x12\r\n\tCANCELLED\x10\x05\x32\xca\x01\n\x0f\x43heckoutService\x12Y\n\x10InitiateCheckout\x12!.checkout.InitiateCheckoutRequest\x1a\".checkout.InitiateCheckoutResponse\x12\\\n\x11GetCheckoutStatus\x12\".checkout.GetCheckoutStatusRequest\x1a#.checkout.GetCheckoutStatusResponseb\x06proto3')
)

_CHECKOUTSTATE = _descriptor.EnumDescriptor(
  name='CheckoutState',
  full_name='checkout.CheckoutState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATE_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCELLED', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=277,
  serialized_end=386,
)
_sym_db.RegisterEnumDescriptor(_CHECKOUTSTATE)

CheckoutState = enum_type_wrapper.EnumTypeWrapper(_CHECKOUTSTATE)
STATE_UNSPECIFIED = 0
PENDING = 1
PROCESSING = 2
COMPLETED = 3
FAILED = 4
CANCELLED = 5



_INITIATECHECKOUTREQUEST = _descriptor.Descriptor(
  name='InitiateCheckoutRequest',
  full_name='checkout.InitiateCheckoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='checkout.InitiateCheckoutRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=70,
)


_INITIATECHECKOUTRESPONSE = _descriptor.Descriptor(
  name='InitiateCheckoutResponse',
  full_name='checkout.InitiateCheckoutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='checkout_id', full_name='checkout.InitiateCheckoutResponse.checkout_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=119,
)


_GETCHECKOUTSTATUSREQUEST = _descriptor.Descriptor(
  name='GetCheckoutStatusRequest',
  full_name='checkout.GetCheckoutStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='checkout_id', full_name='checkout.GetCheckoutStatusRequest.checkout_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=168,
)


_GETCHECKOUTSTATUSRESPONSE = _descriptor.Descriptor(
  name='GetCheckoutStatusResponse',
  full_name='checkout.GetCheckoutStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='checkout_id', full_name='checkout.GetCheckoutStatusResponse.checkout_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='checkout.GetCheckoutStatusResponse.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='checkout.GetCheckoutStatusResponse.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=275,
)

_GETCHECKOUTSTATUSRESPONSE.fields_by_name['state'].enum_type = _CHECKOUTSTATE
DESCRIPTOR.message_types_by_name['InitiateCheckoutRequest'] = _INITIATECHECKOUTREQUEST
DESCRIPTOR.message_types_by_name['InitiateCheckoutResponse'] = _INITIATECHECKOUTRESPONSE
DESCRIPTOR.message_types_by_name['GetCheckoutStatusRequest'] = _GETCHECKOUTSTATUSREQUEST
DESCRIPTOR.message_types_by_name['GetCheckoutStatusResponse'] = _GETCHECKOUTSTATUSRESPONSE
DESCRIPTOR.enum_types_by_name['CheckoutState'] = _CHECKOUTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitiateCheckoutRequest = _reflection.GeneratedProtocolMessageType('InitiateCheckoutRequest', (_message.Message,), dict(
  DESCRIPTOR = _INITIATECHECKOUTREQUEST,
  __module__ = 'checkout_pb2'
  # @@protoc_insertion_point(class_scope:checkout.InitiateCheckoutRequest)
  ))
_sym_db.RegisterMessage(InitiateCheckoutRequest)

InitiateCheckoutResponse = _reflection.GeneratedProtocolMessageType('InitiateCheckoutResponse', (_message.Message,), dict(
  DESCRIPTOR = _INITIATECHECKOUTRESPONSE,
  __module__ = 'checkout_pb2'
  # @@protoc_insertion_point(class_scope:checkout.InitiateCheckoutResponse)
  ))
_sym_db.RegisterMessage(InitiateCheckoutResponse)

GetCheckoutStatusRequest = _reflection.GeneratedProtocolMessageType('GetCheckoutStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCHECKOUTSTATUSREQUEST,
  __module__ = 'checkout_pb2'
  # @@protoc_insertion_point(class_scope:checkout.GetCheckoutStatusRequest)
  ))
_sym_db.RegisterMessage(GetCheckoutStatusRequest)

GetCheckoutStatusResponse = _reflection.GeneratedProtocolMessageType('GetCheckoutStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETCHECKOUTSTATUSRESPONSE,
  __module__ = 'checkout_pb2'
  # @@protoc_insertion_point(class_scope:checkout.GetCheckoutStatusResponse)
  ))
_sym_db.RegisterMessage(GetCheckoutStatusResponse)



_CHECKOUTSERVICE = _descriptor.ServiceDescriptor(
  name='CheckoutService',
  full_name='checkout.CheckoutService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=389,
  serialized_end=591,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitiateCheckout',
    full_name='checkout.CheckoutService.InitiateCheckout',
    index=0,
    containing_service=None,
    input_type=_INITIATECHECKOUTREQUEST,
    output_type=_INITIATECHECKOUTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCheckoutStatus',
    full_name='checkout.CheckoutService.GetCheckoutStatus',
    index=1,
    containing_service=None,
    input_type=_GETCHECKOUTSTATUSREQUEST,
    output_type=_GETCHECKOUTSTATUSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHECKOUTSERVICE)

DESCRIPTOR.services_by_name['CheckoutService'] = _CHECKOUTSERVICE

# @@protoc_insertion_point(module_scope)
