# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import product_pb2 as product__pb2
import product_read_service_pb2 as product__read__service__pb2


class ProductReadServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProductById = channel.unary_unary(
        '/product_read.ProductReadService/GetProductById',
        request_serializer=product__read__service__pb2.GetProductByIdRequest.SerializeToString,
        response_deserializer=product__pb2.Product.FromString,
        )
    self.GetAllProducts = channel.unary_unary(
        '/product_read.ProductReadService/GetAllProducts',
        request_serializer=product__read__service__pb2.GetAllProductsRequest.SerializeToString,
        response_deserializer=product__read__service__pb2.GetAllProductsResponse.FromString,
        )
    self.SearchProducts = channel.unary_unary(
        '/product_read.ProductReadService/SearchProducts',
        request_serializer=product__read__service__pb2.SearchProductsRequest.SerializeToString,
        response_deserializer=product__read__service__pb2.SearchProductsResponse.FromString,
        )


class ProductReadServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetProductById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllProducts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchProducts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductReadServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProductById': grpc.unary_unary_rpc_method_handler(
          servicer.GetProductById,
          request_deserializer=product__read__service__pb2.GetProductByIdRequest.FromString,
          response_serializer=product__pb2.Product.SerializeToString,
      ),
      'GetAllProducts': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllProducts,
          request_deserializer=product__read__service__pb2.GetAllProductsRequest.FromString,
          response_serializer=product__read__service__pb2.GetAllProductsResponse.SerializeToString,
      ),
      'SearchProducts': grpc.unary_unary_rpc_method_handler(
          servicer.SearchProducts,
          request_deserializer=product__read__service__pb2.SearchProductsRequest.FromString,
          response_serializer=product__read__service__pb2.SearchProductsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'product_read.ProductReadService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
