# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import product_lookup_pb2 as product__lookup__pb2


class ProductLookupStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProductById = channel.unary_unary(
        '/product_lookup.ProductLookup/GetProductById',
        request_serializer=product__lookup__pb2.GetProductByIdRequest.SerializeToString,
        response_deserializer=product__lookup__pb2.Product.FromString,
        )


class ProductLookupServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetProductById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductLookupServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProductById': grpc.unary_unary_rpc_method_handler(
          servicer.GetProductById,
          request_deserializer=product__lookup__pb2.GetProductByIdRequest.FromString,
          response_serializer=product__lookup__pb2.Product.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'product_lookup.ProductLookup', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
