# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_read_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import product_pb2 as product__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='product_read_service.proto',
  package='product_read',
  syntax='proto3',
  serialized_pb=_b('\n\x1aproduct_read_service.proto\x12\x0cproduct_read\x1a\rproduct.proto\"#\n\x15GetProductByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x17\n\x15GetAllProductsRequest\"<\n\x16GetAllProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product\"&\n\x15SearchProductsRequest\x12\r\n\x05query\x18\x01 \x01(\t\"<\n\x16SearchProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product2\x97\x02\n\x12ProductReadService\x12G\n\x0eGetProductById\x12#.product_read.GetProductByIdRequest\x1a\x10.product.Product\x12[\n\x0eGetAllProducts\x12#.product_read.GetAllProductsRequest\x1a$.product_read.GetAllProductsResponse\x12[\n\x0eSearchProducts\x12#.product_read.SearchProductsRequest\x1a$.product_read.SearchProductsResponseBe\n(com.community.catalog.proto.product_readP\x01Z7github.com/community-platform/product_read;product_readb\x06proto3')
  ,
  dependencies=[product__pb2.DESCRIPTOR,])




_GETPRODUCTBYIDREQUEST = _descriptor.Descriptor(
  name='GetProductByIdRequest',
  full_name='product_read.GetProductByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='product_read.GetProductByIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=94,
)


_GETALLPRODUCTSREQUEST = _descriptor.Descriptor(
  name='GetAllProductsRequest',
  full_name='product_read.GetAllProductsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=119,
)


_GETALLPRODUCTSRESPONSE = _descriptor.Descriptor(
  name='GetAllProductsResponse',
  full_name='product_read.GetAllProductsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='products', full_name='product_read.GetAllProductsResponse.products', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=181,
)


_SEARCHPRODUCTSREQUEST = _descriptor.Descriptor(
  name='SearchProductsRequest',
  full_name='product_read.SearchProductsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='product_read.SearchProductsRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=221,
)


_SEARCHPRODUCTSRESPONSE = _descriptor.Descriptor(
  name='SearchProductsResponse',
  full_name='product_read.SearchProductsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='products', full_name='product_read.SearchProductsResponse.products', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=283,
)

_GETALLPRODUCTSRESPONSE.fields_by_name['products'].message_type = product__pb2._PRODUCT
_SEARCHPRODUCTSRESPONSE.fields_by_name['products'].message_type = product__pb2._PRODUCT
DESCRIPTOR.message_types_by_name['GetProductByIdRequest'] = _GETPRODUCTBYIDREQUEST
DESCRIPTOR.message_types_by_name['GetAllProductsRequest'] = _GETALLPRODUCTSREQUEST
DESCRIPTOR.message_types_by_name['GetAllProductsResponse'] = _GETALLPRODUCTSRESPONSE
DESCRIPTOR.message_types_by_name['SearchProductsRequest'] = _SEARCHPRODUCTSREQUEST
DESCRIPTOR.message_types_by_name['SearchProductsResponse'] = _SEARCHPRODUCTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetProductByIdRequest = _reflection.GeneratedProtocolMessageType('GetProductByIdRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPRODUCTBYIDREQUEST,
  __module__ = 'product_read_service_pb2'
  # @@protoc_insertion_point(class_scope:product_read.GetProductByIdRequest)
  ))
_sym_db.RegisterMessage(GetProductByIdRequest)

GetAllProductsRequest = _reflection.GeneratedProtocolMessageType('GetAllProductsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETALLPRODUCTSREQUEST,
  __module__ = 'product_read_service_pb2'
  # @@protoc_insertion_point(class_scope:product_read.GetAllProductsRequest)
  ))
_sym_db.RegisterMessage(GetAllProductsRequest)

GetAllProductsResponse = _reflection.GeneratedProtocolMessageType('GetAllProductsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETALLPRODUCTSRESPONSE,
  __module__ = 'product_read_service_pb2'
  # @@protoc_insertion_point(class_scope:product_read.GetAllProductsResponse)
  ))
_sym_db.RegisterMessage(GetAllProductsResponse)

SearchProductsRequest = _reflection.GeneratedProtocolMessageType('SearchProductsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHPRODUCTSREQUEST,
  __module__ = 'product_read_service_pb2'
  # @@protoc_insertion_point(class_scope:product_read.SearchProductsRequest)
  ))
_sym_db.RegisterMessage(SearchProductsRequest)

SearchProductsResponse = _reflection.GeneratedProtocolMessageType('SearchProductsResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHPRODUCTSRESPONSE,
  __module__ = 'product_read_service_pb2'
  # @@protoc_insertion_point(class_scope:product_read.SearchProductsResponse)
  ))
_sym_db.RegisterMessage(SearchProductsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n(com.community.catalog.proto.product_readP\001Z7github.com/community-platform/product_read;product_read'))

_PRODUCTREADSERVICE = _descriptor.ServiceDescriptor(
  name='ProductReadService',
  full_name='product_read.ProductReadService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=286,
  serialized_end=565,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProductById',
    full_name='product_read.ProductReadService.GetProductById',
    index=0,
    containing_service=None,
    input_type=_GETPRODUCTBYIDREQUEST,
    output_type=product__pb2._PRODUCT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllProducts',
    full_name='product_read.ProductReadService.GetAllProducts',
    index=1,
    containing_service=None,
    input_type=_GETALLPRODUCTSREQUEST,
    output_type=_GETALLPRODUCTSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SearchProducts',
    full_name='product_read.ProductReadService.SearchProducts',
    index=2,
    containing_service=None,
    input_type=_SEARCHPRODUCTSREQUEST,
    output_type=_SEARCHPRODUCTSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTREADSERVICE)

DESCRIPTOR.services_by_name['ProductReadService'] = _PRODUCTREADSERVICE

# @@protoc_insertion_point(module_scope)
