# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import product_pb2 as product__pb2


class ProductReadServiceStub(object):
  """The gRPC service definition for reading product data.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SearchProducts = channel.unary_unary(
        '/product.ProductReadService/SearchProducts',
        request_serializer=product__pb2.SearchProductsRequest.SerializeToString,
        response_deserializer=product__pb2.SearchProductsResponse.FromString,
        )


class ProductReadServiceServicer(object):
  """The gRPC service definition for reading product data.
  """

  def SearchProducts(self, request, context):
    """Searches for products based on a query string.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductReadServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SearchProducts': grpc.unary_unary_rpc_method_handler(
          servicer.SearchProducts,
          request_deserializer=product__pb2.SearchProductsRequest.FromString,
          response_serializer=product__pb2.SearchProductsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'product.ProductReadService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
