# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import agent_pb2 as agent__pb2


class AgentServiceStub(object):
  """The Agent service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExecuteWorkflow = channel.unary_stream(
        '/agent.v1.AgentService/ExecuteWorkflow',
        request_serializer=agent__pb2.ExecuteWorkflowRequest.SerializeToString,
        response_deserializer=agent__pb2.ExecuteWorkflowResponse.FromString,
        )


class AgentServiceServicer(object):
  """The Agent service definition.
  """

  def ExecuteWorkflow(self, request, context):
    """Executes a workflow based on a user query.
    This is a streaming RPC, allowing for real-time updates on the workflow's progress.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExecuteWorkflow': grpc.unary_stream_rpc_method_handler(
          servicer.ExecuteWorkflow,
          request_deserializer=agent__pb2.ExecuteWorkflowRequest.FromString,
          response_serializer=agent__pb2.ExecuteWorkflowResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'agent.v1.AgentService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
