# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='agent.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61gent.proto\x12\x08\x61gent.v1\x1a\x1cgoogle/protobuf/struct.proto\",\n\x16\x45xecuteWorkflowRequest\x12\x12\n\nuser_query\x18\x01 \x01(\t\"\xb2\x02\n\x17\x45xecuteWorkflowResponse\x12:\n\x10workflow_started\x18\x01 \x01(\x0b\x32\x1e.agent.v1.WorkflowStartedEventH\x00\x12\x32\n\x0ctool_started\x18\x02 \x01(\x0b\x32\x1a.agent.v1.ToolStartedEventH\x00\x12.\n\ntool_ended\x18\x03 \x01(\x0b\x32\x18.agent.v1.ToolEndedEventH\x00\x12\x36\n\x0eworkflow_ended\x18\x04 \x01(\x0b\x32\x1c.agent.v1.WorkflowEndedEventH\x00\x12\x36\n\x0eworkflow_error\x18\x05 \x01(\x0b\x32\x1c.agent.v1.WorkflowErrorEventH\x00\x42\x07\n\x05\x65vent\"+\n\x14WorkflowStartedEvent\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\"L\n\x10ToolStartedEvent\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12%\n\x05input\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value\"K\n\x0eToolEndedEvent\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12&\n\x06output\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value\",\n\x12WorkflowEndedEvent\x12\x16\n\x0e\x66inal_response\x18\x01 \x01(\t\"+\n\x12WorkflowErrorEvent\x12\x15\n\rerror_message\x18\x01 \x01(\t2h\n\x0c\x41gentService\x12X\n\x0f\x45xecuteWorkflow\x12 .agent.v1.ExecuteWorkflowRequest\x1a!.agent.v1.ExecuteWorkflowResponse0\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_EXECUTEWORKFLOWREQUEST = _descriptor.Descriptor(
  name='ExecuteWorkflowRequest',
  full_name='agent.v1.ExecuteWorkflowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_query', full_name='agent.v1.ExecuteWorkflowRequest.user_query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=99,
)


_EXECUTEWORKFLOWRESPONSE = _descriptor.Descriptor(
  name='ExecuteWorkflowResponse',
  full_name='agent.v1.ExecuteWorkflowResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflow_started', full_name='agent.v1.ExecuteWorkflowResponse.workflow_started', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tool_started', full_name='agent.v1.ExecuteWorkflowResponse.tool_started', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tool_ended', full_name='agent.v1.ExecuteWorkflowResponse.tool_ended', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workflow_ended', full_name='agent.v1.ExecuteWorkflowResponse.workflow_ended', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workflow_error', full_name='agent.v1.ExecuteWorkflowResponse.workflow_error', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='agent.v1.ExecuteWorkflowResponse.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=102,
  serialized_end=408,
)


_WORKFLOWSTARTEDEVENT = _descriptor.Descriptor(
  name='WorkflowStartedEvent',
  full_name='agent.v1.WorkflowStartedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflow_id', full_name='agent.v1.WorkflowStartedEvent.workflow_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=453,
)


_TOOLSTARTEDEVENT = _descriptor.Descriptor(
  name='ToolStartedEvent',
  full_name='agent.v1.ToolStartedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tool_name', full_name='agent.v1.ToolStartedEvent.tool_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input', full_name='agent.v1.ToolStartedEvent.input', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=531,
)


_TOOLENDEDEVENT = _descriptor.Descriptor(
  name='ToolEndedEvent',
  full_name='agent.v1.ToolEndedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tool_name', full_name='agent.v1.ToolEndedEvent.tool_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output', full_name='agent.v1.ToolEndedEvent.output', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=608,
)


_WORKFLOWENDEDEVENT = _descriptor.Descriptor(
  name='WorkflowEndedEvent',
  full_name='agent.v1.WorkflowEndedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='final_response', full_name='agent.v1.WorkflowEndedEvent.final_response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=610,
  serialized_end=654,
)


_WORKFLOWERROREVENT = _descriptor.Descriptor(
  name='WorkflowErrorEvent',
  full_name='agent.v1.WorkflowErrorEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_message', full_name='agent.v1.WorkflowErrorEvent.error_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=656,
  serialized_end=699,
)

_EXECUTEWORKFLOWRESPONSE.fields_by_name['workflow_started'].message_type = _WORKFLOWSTARTEDEVENT
_EXECUTEWORKFLOWRESPONSE.fields_by_name['tool_started'].message_type = _TOOLSTARTEDEVENT
_EXECUTEWORKFLOWRESPONSE.fields_by_name['tool_ended'].message_type = _TOOLENDEDEVENT
_EXECUTEWORKFLOWRESPONSE.fields_by_name['workflow_ended'].message_type = _WORKFLOWENDEDEVENT
_EXECUTEWORKFLOWRESPONSE.fields_by_name['workflow_error'].message_type = _WORKFLOWERROREVENT
_EXECUTEWORKFLOWRESPONSE.oneofs_by_name['event'].fields.append(
  _EXECUTEWORKFLOWRESPONSE.fields_by_name['workflow_started'])
_EXECUTEWORKFLOWRESPONSE.fields_by_name['workflow_started'].containing_oneof = _EXECUTEWORKFLOWRESPONSE.oneofs_by_name['event']
_EXECUTEWORKFLOWRESPONSE.oneofs_by_name['event'].fields.append(
  _EXECUTEWORKFLOWRESPONSE.fields_by_name['tool_started'])
_EXECUTEWORKFLOWRESPONSE.fields_by_name['tool_started'].containing_oneof = _EXECUTEWORKFLOWRESPONSE.oneofs_by_name['event']
_EXECUTEWORKFLOWRESPONSE.oneofs_by_name['event'].fields.append(
  _EXECUTEWORKFLOWRESPONSE.fields_by_name['tool_ended'])
_EXECUTEWORKFLOWRESPONSE.fields_by_name['tool_ended'].containing_oneof = _EXECUTEWORKFLOWRESPONSE.oneofs_by_name['event']
_EXECUTEWORKFLOWRESPONSE.oneofs_by_name['event'].fields.append(
  _EXECUTEWORKFLOWRESPONSE.fields_by_name['workflow_ended'])
_EXECUTEWORKFLOWRESPONSE.fields_by_name['workflow_ended'].containing_oneof = _EXECUTEWORKFLOWRESPONSE.oneofs_by_name['event']
_EXECUTEWORKFLOWRESPONSE.oneofs_by_name['event'].fields.append(
  _EXECUTEWORKFLOWRESPONSE.fields_by_name['workflow_error'])
_EXECUTEWORKFLOWRESPONSE.fields_by_name['workflow_error'].containing_oneof = _EXECUTEWORKFLOWRESPONSE.oneofs_by_name['event']
_TOOLSTARTEDEVENT.fields_by_name['input'].message_type = google_dot_protobuf_dot_struct__pb2._VALUE
_TOOLENDEDEVENT.fields_by_name['output'].message_type = google_dot_protobuf_dot_struct__pb2._VALUE
DESCRIPTOR.message_types_by_name['ExecuteWorkflowRequest'] = _EXECUTEWORKFLOWREQUEST
DESCRIPTOR.message_types_by_name['ExecuteWorkflowResponse'] = _EXECUTEWORKFLOWRESPONSE
DESCRIPTOR.message_types_by_name['WorkflowStartedEvent'] = _WORKFLOWSTARTEDEVENT
DESCRIPTOR.message_types_by_name['ToolStartedEvent'] = _TOOLSTARTEDEVENT
DESCRIPTOR.message_types_by_name['ToolEndedEvent'] = _TOOLENDEDEVENT
DESCRIPTOR.message_types_by_name['WorkflowEndedEvent'] = _WORKFLOWENDEDEVENT
DESCRIPTOR.message_types_by_name['WorkflowErrorEvent'] = _WORKFLOWERROREVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecuteWorkflowRequest = _reflection.GeneratedProtocolMessageType('ExecuteWorkflowRequest', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTEWORKFLOWREQUEST,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.v1.ExecuteWorkflowRequest)
  ))
_sym_db.RegisterMessage(ExecuteWorkflowRequest)

ExecuteWorkflowResponse = _reflection.GeneratedProtocolMessageType('ExecuteWorkflowResponse', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTEWORKFLOWRESPONSE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.v1.ExecuteWorkflowResponse)
  ))
_sym_db.RegisterMessage(ExecuteWorkflowResponse)

WorkflowStartedEvent = _reflection.GeneratedProtocolMessageType('WorkflowStartedEvent', (_message.Message,), dict(
  DESCRIPTOR = _WORKFLOWSTARTEDEVENT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.v1.WorkflowStartedEvent)
  ))
_sym_db.RegisterMessage(WorkflowStartedEvent)

ToolStartedEvent = _reflection.GeneratedProtocolMessageType('ToolStartedEvent', (_message.Message,), dict(
  DESCRIPTOR = _TOOLSTARTEDEVENT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.v1.ToolStartedEvent)
  ))
_sym_db.RegisterMessage(ToolStartedEvent)

ToolEndedEvent = _reflection.GeneratedProtocolMessageType('ToolEndedEvent', (_message.Message,), dict(
  DESCRIPTOR = _TOOLENDEDEVENT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.v1.ToolEndedEvent)
  ))
_sym_db.RegisterMessage(ToolEndedEvent)

WorkflowEndedEvent = _reflection.GeneratedProtocolMessageType('WorkflowEndedEvent', (_message.Message,), dict(
  DESCRIPTOR = _WORKFLOWENDEDEVENT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.v1.WorkflowEndedEvent)
  ))
_sym_db.RegisterMessage(WorkflowEndedEvent)

WorkflowErrorEvent = _reflection.GeneratedProtocolMessageType('WorkflowErrorEvent', (_message.Message,), dict(
  DESCRIPTOR = _WORKFLOWERROREVENT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.v1.WorkflowErrorEvent)
  ))
_sym_db.RegisterMessage(WorkflowErrorEvent)



_AGENTSERVICE = _descriptor.ServiceDescriptor(
  name='AgentService',
  full_name='agent.v1.AgentService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=701,
  serialized_end=805,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExecuteWorkflow',
    full_name='agent.v1.AgentService.ExecuteWorkflow',
    index=0,
    containing_service=None,
    input_type=_EXECUTEWORKFLOWREQUEST,
    output_type=_EXECUTEWORKFLOWRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENTSERVICE)

DESCRIPTOR.services_by_name['AgentService'] = _AGENTSERVICE

# @@protoc_insertion_point(module_scope)
